version: '3.8'

services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #restart: always
  #php
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      # - /var/www/html/vendor
      - ./app:/var/www/html/
  #mysql
  db:
    image: mysql:8.2
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped #it will restart automatically in case 
    #of any fault, but container can be stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

   #redis
volumes:
  mysqldata: